### ISSUE TITLE
EPIC - Set up Platform and Workspaces 

### ISSUE THREAD

**Issue by Christina5P** [Christina5P/SustainLuxe#6]
Acceptance criteria: a workspace mfor coding and needed platforms and frameworks

Tasks:

- [x] Set up repository in GitHub #7 
- [x]  Set up workspace GitPod #8 
- [x] Install Django, Frameworks, Libary and apps #9  
- [x] Set up Stripe #11 
- [x] Set up AWS #12 
- [x] Set up Heroku #13
